# Cart2Insights - SQL Analysis

## Objective

To analyze e-commerce performance using SQL queries on the Cart2Insights MySQL database.

## Database

Database: cart2insights

## Tables

- customers
- orders
- order_items
- order_payments
- order_reviews
- products
- sellers
- geolocation

In [1]:
%pip install pymysql

Collecting pymysql
  Using cached pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Using cached pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pymysql

print("PyMySQL is working!")

PyMySQL is working!

In [2]:
from sqlalchemy import create_engine

print("SQLAlchemy is working!")

SQLAlchemy is working!

In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
engine = create_engine(
    "mysql+pymysql://root:Shyam09.@localhost:3306/cart2insights"
)

In [5]:
query = "SELECT DATABASE();"

result = pd.read_sql(query, engine)

result

      DATABASE()
0  cart2insights

In [6]:
query = "SHOW TABLES;"

tables = pd.read_sql(query, engine)

tables

             Tables_in_cart2insights
0                          customers
1                        geolocation
2                        order_items
3                     order_payments
4                      order_reviews
5                             orders
6  product_category_name_translation
7                           products
8                            sellers

## 1. Business Overview

In [ ]:
//Total Customers
query = """
SELECT COUNT(*) AS total_customers
FROM customers;
"""

total_customers = pd.read_sql(query, engine)

total_customers

   total_customers
0            99441

In [ ]:
//total_orders
query = """
SELECT COUNT(*) AS total_orders
FROM orders;
"""

total_orders = pd.read_sql(query, engine)

total_orders

   total_orders
0         35863

In [ ]:
//Total Products
query = """
SELECT COUNT(*) AS total_products
FROM products;
"""

total_products = pd.read_sql(query, engine)

total_products


//Total Sellers
query = """
SELECT COUNT(*) AS total_sellers
FROM sellers;
"""

total_sellers = pd.read_sql(query, engine)

query = """
SELECT COUNT(*) AS total_sellers
FROM sellers;
"""

total_sellers = pd.read_sql(query, engine)

total_sellers

total_sellers

//Total Revenue
query = """
SELECT
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM order_payments;
"""

total_revenue = pd.read_sql(query, engine)

total_revenue
//Average Order Value

query = """
SELECT
    ROUND(
        SUM(payment_value) /
        COUNT(DISTINCT order_id),
        2
    ) AS average_order_value
FROM order_payments;
"""

average_order_value = pd.read_sql(query, engine)

average_order_value

   average_order_value
0               156.77

In [14]:
query = """
SELECT
    (SELECT COUNT(*) FROM customers) AS total_customers,

    (SELECT COUNT(*) FROM orders) AS total_orders,

    (SELECT COUNT(*) FROM products) AS total_products,

    (SELECT COUNT(*) FROM sellers) AS total_sellers,

    (SELECT ROUND(SUM(payment_value), 2)
     FROM order_payments) AS total_revenue,

    (SELECT ROUND(
        SUM(payment_value) /
        COUNT(DISTINCT order_id),
        2
    )
    FROM order_payments) AS average_order_value;
"""

business_overview = pd.read_sql(query, engine)

business_overview

,total_customers,total_orders,total_products,total_sellers,total_revenue,average_order_value
0,99441,35863,32341,3095,1273266.29,156.77

## 2. Sales Analysis

In [ ]:
// Orders by Status
query = """
SELECT
    order_status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC;
"""

orders_by_status = pd.read_sql(query, engine)

orders_by_status

  order_status  total_orders
0    delivered         35861
1     canceled             2

In [ ]:
//Revenue by Payment Type
query = """
SELECT
    payment_type,
    ROUND(SUM(payment_value), 2) AS revenue
FROM order_payments
GROUP BY payment_type
ORDER BY revenue DESC;
"""

revenue_by_payment = pd.read_sql(query, engine)

revenue_by_payment

//Orders by Payment Type
query = """
SELECT
    payment_type,
    COUNT(DISTINCT order_id) AS total_orders
FROM order_payments
GROUP BY payment_type
ORDER BY total_orders DESC;
"""

orders_by_payment = pd.read_sql(query, engine)

orders_by_payment

  payment_type  total_orders
0  credit_card          6196
1       boleto          1488
2      voucher           368
3   debit_card           112

### Monthly Revenue

In [18]:
query = """
SELECT
    YEAR(o.order_purchase_timestamp) AS year,
    MONTH(o.order_purchase_timestamp) AS month,
    ROUND(SUM(p.payment_value), 2) AS revenue
FROM orders o
JOIN order_payments p
    ON o.order_id = p.order_id
GROUP BY
    YEAR(o.order_purchase_timestamp),
    MONTH(o.order_purchase_timestamp)
ORDER BY
    year,
    month;
"""

monthly_revenue = pd.read_sql(query, engine)

monthly_revenue

    year  month    revenue
0   2016     10    3084.31
1   2017      1    8030.82
2   2017      2   24038.95
3   2017      3   30003.15
4   2017      4   29074.01
5   2017      5   42415.10
6   2017      6   41774.93
7   2017      7   50889.69
8   2017      8   57594.19
9   2017      9   51584.75
10  2017     10   60478.93
11  2017     11  104956.33
12  2017     12   64635.09
13  2018      1   92306.01
14  2018      2   75273.29
15  2018      3   99936.18
16  2018      4  101762.80
17  2018      5   93248.00
18  2018      6   79214.79
19  2018      7   81747.95
20  2018      8   81217.02

## 3. Customer Analysis

In [ ]:
//Customers by State

query = """
SELECT
    customer_state,
    COUNT(*) AS total_customers
FROM customers
GROUP BY customer_state
ORDER BY total_customers DESC;
"""

customers_by_state = pd.read_sql(query, engine)

customers_by_state


//Top Customer Cities
query = """
SELECT
    customer_city,
    customer_state,
    COUNT(*) AS total_customers
FROM customers
GROUP BY
    customer_city,
    customer_state
ORDER BY total_customers DESC
LIMIT 10;
"""

top_customer_cities = pd.read_sql(query, engine)

top_customer_cities

           customer_city customer_state  total_customers
0              sao paulo             SP            15540
1         rio de janeiro             RJ             6882
2         belo horizonte             MG             2773
3               brasilia             DF             2131
4               curitiba             PR             1521
5               campinas             SP             1444
6           porto alegre             RS             1379
7               salvador             BA             1245
8              guarulhos             SP             1189
9  sao bernardo do campo             SP              938

## 4. Product Analysis

In [ ]:
//Top Categories
query = """
SELECT
    p.product_category_name,
    COUNT(*) AS items_sold
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY items_sold DESC
LIMIT 10;
"""

top_categories = pd.read_sql(query, engine)

top_categories


//Category Revenue
query = """
SELECT
    p.product_category_name,
    ROUND(SUM(oi.price), 2) AS revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY revenue DESC
LIMIT 10;
"""

category_revenue = pd.read_sql(query, engine)

category_revenue

    product_category_name   revenue
0      relogios_presentes  96362.20
1            beleza_saude  93848.28
2         cama_mesa_banho  79410.27
3  informatica_acessorios  79345.80
4           esporte_lazer  74600.14
5        moveis_decoracao  62642.17
6   utilidades_domesticas  50982.25
7              cool_stuff  49895.74
8              automotivo  45102.08
9              brinquedos  43752.60

## 5. Seller Analysis

In [ ]:
// Top Sellers
query = """
SELECT
    seller_id,
    COUNT(*) AS items_sold
FROM order_items
GROUP BY seller_id
ORDER BY items_sold DESC
LIMIT 10;
"""

top_sellers = pd.read_sql(query, engine)

top_sellers


 //Seller Revenue
query = """
SELECT
    seller_id,
    ROUND(SUM(price), 2) AS revenue
FROM order_items
GROUP BY seller_id
ORDER BY revenue DESC
LIMIT 10;
"""

seller_revenue = pd.read_sql(query, engine)

seller_revenue

                          seller_id   revenue
0  53243585a1d6dc2643021fd1853d8905  24432.20
1  4869f7a5dfa277a7dca6462dcf3b52b2  19345.47
2  7c67e1448b00f6e969d365cea6b010ab  17192.60
3  fa1c13f2614d7b5c4749cbc52fecda94  15661.52
4  b37c4c02bda3161a7546a4e6d222d5b2  13440.00
5  4a3ca9315b744ce9f8e9374361493884  13131.50
6  7e93a43ef30c4f03f38b393420bc753a  12917.70
7  46dc3b2cc0980fb8ec44634e21d2718e  12822.46
8  1025f0e2d44d7041d6cf58b6550e0bfa  12272.67
9  da8622b14eb17ae2831f4ac5b9dab84a  12242.77

## 6. Delivery Analysis

In [26]:
//Average Delivery Time
query = """
SELECT
    ROUND(
        AVG(
            DATEDIFF(
                order_delivered_customer_date,
                order_purchase_timestamp
            )
        ),
        2
    ) AS average_delivery_days
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;
"""

average_delivery = pd.read_sql(query, engine)

average_delivery
//Late vs On-Time

query = """
SELECT
    CASE
        WHEN order_delivered_customer_date >
             order_estimated_delivery_date
        THEN 'Late'
        ELSE 'On Time'
    END AS delivery_status,

    COUNT(*) AS total_orders

FROM orders

WHERE order_delivered_customer_date IS NOT NULL
  AND order_estimated_delivery_date IS NOT NULL

GROUP BY delivery_status;
"""

delivery_performance = pd.read_sql(query, engine)

delivery_performance

  delivery_status  total_orders
0         On Time         33015
1            Late          2848

## 7. Customer Experience

In [33]:
query = """
SELECT
    review_score,
    COUNT(*) AS total_reviews
FROM order_reviews
GROUP BY review_score
ORDER BY review_score;
"""

review_distribution = pd.read_sql(query, engine)

review_distribution

query = """
SELECT
    ROUND(AVG(review_score), 2) AS average_review_score
FROM order_reviews;
"""

average_review = pd.read_sql(query, engine)

average_review

   average_review_score
0                  4.14

### Product Categories With More Than 1000 Items Sold

In [29]:
query = """
SELECT
    p.product_category_name,
    COUNT(*) AS items_sold
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY p.product_category_name
HAVING COUNT(*) > 1000
ORDER BY items_sold DESC;
"""

categories_over_1000 = pd.read_sql(query, engine)

categories_over_1000

Empty DataFrame
Columns: [product_category_name, items_sold]
Index: []

## 8. Window Function Analysis

In [30]:
query = """
SELECT
    product_category_name,
    revenue,
    RANK() OVER (
        ORDER BY revenue DESC
    ) AS revenue_rank
FROM (
    SELECT
        p.product_category_name,
        SUM(oi.price) AS revenue
    FROM order_items oi
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY p.product_category_name
) AS category_revenue
ORDER BY revenue_rank;
"""

category_ranking = pd.read_sql(query, engine)

category_ranking.head(20)

     product_category_name   revenue  revenue_rank
0       relogios_presentes  96362.20             1
1             beleza_saude  93848.28             2
2          cama_mesa_banho  79410.27             3
3   informatica_acessorios  79345.80             4
4            esporte_lazer  74600.14             5
5         moveis_decoracao  62642.17             6
6    utilidades_domesticas  50982.25             7
7               cool_stuff  49895.74             8
8               automotivo  45102.08             9
9               brinquedos  43752.60            10
10      ferramentas_jardim  40925.17            11
11              perfumaria  34444.73            12
12                   bebes  32481.94            13
13               telefonia  25848.55            14
14                     pcs  25294.93            15
15       moveis_escritorio  22598.85            16
16               papelaria  17418.34            17
17         eletroportateis  16701.01            18
18          telefonia_fixa  14461.20            19
19                pet_shop  14291.43            20

In [34]:
query = "SHOW TABLES;"

tables = pd.read_sql(query, engine)

tables

             Tables_in_cart2insights
0                          customers
1                        geolocation
2                        order_items
3                     order_payments
4                      order_reviews
5                             orders
6  product_category_name_translation
7                           products
8                            sellers